### ISSUE TITLE
[FEATURE] Create a method to get context with @ViewChild

### ISSUE THREAD

**Issue by manhnd98** [ng-web-apis/canvas#7]
# 🚀 Feature request

### Is your feature request related to a problem?

I'm using this library for my personal project. However, It has some unsupported features such as [translate](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/translate)
### Describe the solution you'd like
`  @ViewChild(Canvas2dDirective, { static: true, read: Canvas2dDirective })
  private canvasDirective!: Canvas2dDirective;`

` const ctx = this.canvas2dDirective.getContext();`

**Comment by waterplea** [comment]
Hi there. Yes, we still need to implement translate but there's no time unfortunately :( As for your feature request — you can just do:
```ts
@ViewChild(Canvas2dDirective, { static: true, read: CANVAS_2D_CONTEXT })
```
Or even
```ts
@ViewChild(CANVAS_2D_CONTEXT)
```
If it's the only instance in your template.
